spring:
    profiles:
        active:
            - dev
---
server:
    port: 8201
spring:
    profiles: dev  #开发环境
    application:
        name: microservice-config-client
        
---
eureka:
    client:
        server-url:
            defaultZone: http://eureka-dev.com:7001/eureka/


---
        
 #请保存为UTF-8的格式
