spring:
    profiles:
        active:
            - dev
---
server:
    port: 8201
    
spring:
    profiles: dev  #开发环境
    application:
        name: microservice-config-client
        
---
eureka:
    client:
        service-url:
            defaultZone: http://eureka-dev.com:7001/eureka/
      

# 注册中心职责是维护服务实例，false：不检索服务。
#ureka.client.fetch-registry=false
#eureka.client.service-url.defaultZone
---
server:
    port: 8202
    
spring:
    profiles: test  #开发环境
    application:
        name: microservice-config-client
---
eureka:
    client:
        service-url:
            defaultZone: http://eureka-test.com:7001/eureka/    
 #请保存为UTF-8的格式
