spring:
    profiles:
        active:
            - dev
---

spring:
    profiles: dev  #开发环境
    application:
        name: microservice-config-run-dev
        
---
spring:
     profiles: test 
     application:
        name: microservice-config-run-test
        
 #请保存为UTF-8的格式
